
// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using christ.Xncf.WechatMessage.Models.DatabaseModel;

namespace christ.Xncf.WechatMessage.Migrations.Migrations.SQLite
{
    [DbContext(typeof(WechatMessageSenparcEntities))]
    [Migration("20201220114801_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6");
#pragma warning restore 612, 618
        }
    }
}
