
// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using christ.Xncf.demoNet5.Models.DatabaseModel;

namespace christ.Xncf.demoNet5.Migrations.Migrations.SQLite
{
    [DbContext(typeof(demoNet5SenparcEntities))]
    [Migration("20201220111039_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6");
#pragma warning restore 612, 618
        }
    }
}
